"""
Django settings for Rafaflix project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os # para vercel


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-64=fnzcj*k4lx+f3@+$4r4r=nz$4b!xl0-k4%p*98-#0wt7%ti'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app', '127.0.0.1', '.now.sh', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filme',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Rafaflix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"], # BASE_DIR / "templates",
        'APP_DIRS': True, # carrega os templates de cada appddddd
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'filme.context.lista_filmes_recentes', # carrega o contexto de filmes recentes
                'filme.context.lista_filmes_emalta', # carrega o contexto de filmes em alta
            
            ],
        },
    },
]

# WSGI_APPLICATION = 'Rafaflix.wsgi.application'
WSGI_APPLICATION = 'Rafaflix.wsgi.app' # para vercel


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """

DATABASES = {
    
    'default': {
        
       'ENGINE': 'django.db.backends.postgresql', 
       'NAME': 'vercel',
       'USER': 'default',
       'PASSWORD': 'I0cDZRpt9noa',
       'HOST': 'ep-cold-darkness-403869-pooler.us-east-1.postgres.vercel-storage.com',
       'PORT': '5432',
    
}
    
}

""" import dj_database_url # para vercel

DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True) # para vercel """

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'filme.Usuario' # mudar o modelo de usuario para o criado em filme\models.py app+classename

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_ROOT = BASE_DIR / 'staticfiles' white noise

STATIC_URL = 'static/'

"""STATICFILES_DIRS = [
    BASE_DIR / "static",
]"""

STATICFILES_DIRS = os.path.join(BASE_DIR, 'static')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static' )


MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# COMANDOS PARA QUE TENHA CONTROLE DE USUARIO

LOGIN_REDIRECT_URL = 'filme:homefilmes' # redireciona para a pagina homefilmes , os dois pontos eh pra levar a uma url

LOGIN_URL = 'filme:login' # redireciona para a pagina de login

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'

CRISPY_TEMPLATE_PACK = 'bootstrap5'

DATABASES = {
    
    'default': {
        
       'ENGINE': 'django.db.backends.postgresql', 
       'NAME': 'vercel',
       'USER': 'default',
       'PASSWORD': 'I0cDZRpt9noa',
       'HOST': 'ep-cold-darkness-403869-pooler.us-east-1.postgres.vercel-storage.com',
       'PORT': '5432',
    
}
    
}