# Generated by Django 4.2.3 on 2023-07-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episodios',
            new_name='Episodio',
        ),
    ]
